---
# Obsidian Web Addon - Handlers

- name: reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded

- name: restart syncthing
  ansible.builtin.systemd:
    name: syncthing
    state: restarted
    scope: user
  become_user: "{{ obsidian_syncthing_user }}"

- name: restart quartz-build timer
  ansible.builtin.systemd:
    name: quartz-build.timer
    state: restarted
    daemon_reload: true
