---
# Immich Addon - Handlers

- name: restart immich
  community.docker.docker_compose_v2:
    project_src: "{{ immich_data_path }}"
    state: restarted

- name: reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded

- name: restart immich backup timer
  ansible.builtin.systemd:
    name: immich-backup.timer
    state: restarted
    daemon_reload: true
